services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
